# Generated by Django 2.2.10 on 2021-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(null=True, to='chat.Message'),
        ),
    ]
