# Generated by Django 2.2.10 on 2021-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210517_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Message'),
        ),
    ]
