# Generated by Django 2.2.10 on 2021-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210518_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
    ]
