# Generated by Django 2.2.10 on 2021-05-17 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('1d5fc500-1b48-49a7-9d10-274353aed045'), editable=False, null=True, unique=True),
        ),
    ]
