# Generated by Django 2.2.10 on 2021-05-17 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210517_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('43b6c3f4-8e1a-447d-816f-eb3b76e1eb46'), editable=False, null=True, unique=True),
        ),
    ]
