# Generated by Django 2.2.10 on 2021-05-17 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210517_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('b580ce62-f9c1-43d0-94f8-c8c321974d5a'), editable=False, null=True, unique=True),
        ),
    ]
