# Generated by Django 2.2.10 on 2021-05-18 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210517_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('6b8f9f11-b22a-41bb-a002-487dc3acc3e6'), editable=False, null=True, unique=True),
        ),
    ]
