# Generated by Django 2.2.10 on 2021-05-18 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210518_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('3c94d2da-9b4c-4aea-8017-0ac1e58e7379'), editable=False, null=True, unique=True),
        ),
    ]
