# Generated by Django 2.2.10 on 2021-05-19 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210518_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_chat_id',
            field=models.UUIDField(default=uuid.UUID('c3703752-608f-4273-9809-383e5bc12850'), editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='helo', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
